#!/bin/bash

# Capture both the response headers and body by sending the -i option to curl.
response=$(curl -i -w '\n' -s "$@")

# Extract the x-openwhisk-activation-id from the headers.
activation_id=$(echo "$response" | grep 'x-openwhisk-activation-id:' | awk '{print $2}' | tr -d '\r')

# Print the response payload
payload=$(echo "$response" | sed -n '/{/,/}/p')

# Print the times, response, and activation ID.
curl -w @- -s "$@" <<EOF
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
Response Payload: $payload\n
OpenWhisk Activation ID: $activation_id\n
EOF
